### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by mikeytj** [T5ive/Tools-Injector-Mod-Menu#3] opened 2021-08-03 10:09 UTC
hello I have this issue when trying to compile

13:08:08 PM [Success] Deleted C:\Users\mozsh\AppData\Local\Temp\TFiveMenu
13:08:08 PM [Success] Extract Default.zip
To => C:\Users\morsh\AppData\Local\Temp\TFiveMenu
13:08:08 PM [Success] Extract Default.zip
To => C:\Users\morsh\AppData\Local\Temp\TFiveMenu
13:08:08 PM [Success] Replaced MainActivity.smali
13:08:08 PM [Success] Replaced Android.mk
13:08:08 PM [Success] Replaced Application.mk
13:08:08 PM [Success] Replaced Menu.h (Credit)
**13:08:11 PM [Error:015] StartIndex cannot be less than zero.
Parameter name: startIndex
13:08:12 PM [Error:018] Failed to Replace Something**

**Comment by T5ive** [comment] 2021-08-03 13:51
uncheck "Remove modified files"
after compile press "Temp modify directory"
in folder "jni" copy "Main.cpp" to me (dont forget to remove every patch offset)
If possible, take a screenshot of the "menu patch" as well.

ps. what version are you using?

**Comment by mikeytj** [comment] 2021-08-04 04:52
Hello, thank you for your reply.

I have attached the main.cpp file below. The version I am using is 1.3.1 which is the latest. Before that, I was using 1.2.6 and it worked fine, even now when I try to compile the same game with the 1.2.6 version it works fine. 

i have attached both main.cpp and menu.h inside the zip

[files.zip](https://github.com/T5ive/Tools-Injector-Mod-Menu/files/6928765/files.zip)

**Comment by T5ive** [comment] 2021-08-04 07:42
I still can't find a clear problem.
Every compiled are problem?
You try this file If it doesn't bother you, please tell me again.

However, I am developing a function to detect this error.

[Pig Hog.zip](https://github.com/T5ive/Tools-Injector-Mod-Menu/files/6929468/Pig.Hog.zip)

**Comment by T5ive** [comment] 2021-08-04 07:47
Oh, I finally found it.
The problem is with the Toast.
Please add 1 Toast.
I will fix it in the next version.

**Comment by mikeytj** [comment] 2021-08-04 09:47
Hello Pig Hog xml file also gives the same error, "Please add 1 Toast." do you mean adding from the Main Menu Settings of the tool? If so i have added it but the error continues.

**Comment by mikeytj** [comment] 2021-08-04 09:52
Ok never it worked now :) i removed the toast all together and added again and it worked :)

**Comment by mikeytj** [comment] 2021-08-04 10:31
it looks like when i closed and reopen the tool the error came back :/

**Comment by T5ive** [comment] 2021-08-04 11:19
please you upload settings.json

**Comment by mikeytj** [comment] 2021-08-04 12:39
[json.zip](https://github.com/T5ive/Tools-Injector-Mod-Menu/files/6931302/json.zip)

**Comment by mikeytj** [comment] 2021-08-04 12:40
Your tool is really amazing, i just hope I can make the latest version work.

**Comment by T5ive** [comment] 2021-08-04 13:16
> 
> 
> [json.zip](https://github.com/T5ive/Tools-Injector-Mod-Menu/files/6931302/json.zip)

I have tried your settings. but i don't have any error.

However, version 1.4 has been released.

**Comment by mikeytj** [comment] 2021-08-04 14:29
let me try the latest version

**Comment by T5ive** [comment] 2021-08-04 16:01
version 1.4.2 should be fine

**Comment by mikeytj** [comment] 2021-08-04 18:57
Hey thank you for your time, but I keep getting that error, for example when I first load the pig hog XML file and compile, everything goes smoothly but when I try to compile it again I get the error, or when I try to compile my own mod after that, when I compile my mod at first I get the error but when I load your file it goes smoothly at first but the second time it gives the error. As you said it works fine on your end, so I will probably have to figure out what is causing the issue, maybe something up with my PC.

**Comment by T5ive** [comment] 2021-08-04 20:31
Do you have discord?
Please leave your id and I'll get back to you

**Comment by mikeytj** [comment] 2021-08-05 05:43
Hey yes its camlais#1773

**Comment by T5ive** [comment] 2021-08-13 09:41
Please try these.
Please tell me which one is pass (does not get error).
https://drive.google.com/file/d/1bExdHOuNU6HIxGW1EYEkFYUX6w9Vlo8K/view?usp=sharing
*Please read in discord, sent a long time ago.

**Comment by darnkez** [comment] 2021-08-13 13:27
have same issue, and your pig hog file are success compiled

**Comment by T5ive** [comment] 2021-08-13 14:53
> 
> 
> have same issue, and your pig hog file are success compiled

Please try these.
Please tell me which one is pass (does not get error).
drive.google.com/file/d/1bExdHOuNU6HIxGW1EYEkFYUX6w9Vlo8K/view?usp=sharing

leave your discord id, i'll contact

**Comment by T5ive** [comment] 2021-08-13 19:27
The problem was fixed in 1.4.3

The problem is, the hook isn't added
But the program ordered to delete the new line in the hook method (NewMethod)

The reason I've never encountered this problem is because I've never tried the only patch type in the new version

**Closed as completed** 2021-08-13 19:34 UTC
Labels: bug

**Comment by darnkez** [comment] 2021-08-13 23:42
[Success] {07:36:51 AM} Dumped Apk
[Success] {07:37:31 AM} Decompiled APK file
[Success] {07:37:31 AM} Deleted C:\Users\user\AppData\Local\Temp\TFiveMenu\jni
[Success] {07:37:31 AM} Deleted C:\Users\user\AppData\Local\Temp\TFiveMenu\libs
[Success] {07:37:31 AM} Deleted C:\Users\user\AppData\Local\Temp\TFiveMenu\obj
[Success] {07:37:31 AM} Extract Default.zip
To => C:\Users\user\AppData\Local\Temp\TFiveMenu
[Success] {07:37:32 AM} Extract Default.zip
To => C:\Users\user\AppData\Local\Temp\TFiveMenu
[Success] {07:37:32 AM} Replaced MainActivity.smali
[Success] {07:37:32 AM} Replaced Android.mk
[Success] {07:37:32 AM} Replaced Application.mk
[Success] {07:37:32 AM} Replaced Menu.h (Credit)
[Success] {07:37:32 AM} Replaced AndroidManifest.xml
[Success] {07:37:32 AM} Replaced OnCreate
[Success] {07:37:32 AM} Replaced Main.cpp
[Success] {07:37:32 AM} Move C:\Users\user\AppData\Local\Temp\TFiveMenu\com
To => D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\Output\sfr197\smali\com
[Compile] {07:37:32 AM} Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
[Compile] {07:37:32 AM} [arm64-v8a] Compile++      : wcj <= Main.cpp
[Compile] {07:37:46 AM} [arm64-v8a] Compile        : wcj <= hde64.c
[Compile] {07:37:46 AM} [arm64-v8a] Compile++      : wcj <= SubstrateDebug.cpp
[Compile] {07:37:48 AM} [arm64-v8a] Compile++      : wcj <= SubstrateHook.cpp
[Compile] {07:37:49 AM} [arm64-v8a] Compile++      : wcj <= SubstratePosixMemory.cpp
[Compile] {07:37:51 AM} [arm64-v8a] Compile++      : wcj <= SymbolFinder.cpp
[Compile] {07:37:55 AM} [arm64-v8a] Compile++      : wcj <= KittyMemory.cpp
[Compile] {07:37:57 AM} [arm64-v8a] Compile++      : wcj <= MemoryPatch.cpp
[Compile] {07:38:00 AM} [arm64-v8a] Compile++      : wcj <= MemoryBackup.cpp
[Compile] {07:38:02 AM} [arm64-v8a] Compile++      : wcj <= KittyUtils.cpp
[Compile] {07:38:05 AM} [arm64-v8a] Compile++      : wcj <= And64InlineHook.cpp
[Compile] {07:38:05 AM} [arm64-v8a] SharedLibrary  : libwcj.so
[Compile] {07:38:06 AM} [arm64-v8a] Install        : libwcj.so => libs/arm64-v8a/libwcj.so
[Success] {07:38:06 AM} Move C:\Users\user\AppData\Local\Temp\TFiveMenu\libs
To => D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\Output\sfr197\lib
[Success] {07:38:06 AM} Move D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\Output\sfr197\smali\com
To => D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\BuildTools\ApkTarget\smali_classes3\com
[Success] {07:38:06 AM} Move D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\Output\sfr197\lib\arm64-v8a
To => D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\BuildTools\ApkTarget\lib\arm64-v8a
[Success] {07:39:14 AM} Compiled D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\Output\sfr197\sfr197.apk
[Success] {07:39:15 AM} Signed D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\Output\sfr197\sfr197-Signed.apk
[Error:033] {07:39:15 AM} Exception in thread "main" com.android.apksig.apk.ApkFormatException: Malformed APK: not a ZIP archive
[Error:033] {07:39:15 AM} 	at com.android.apksig.ApkSigner.sign(ApkSigner.java:235)
[Error:033] {07:39:15 AM} 	at com.android.apksig.ApkSigner.sign(ApkSigner.java:214)
[Error:033] {07:39:15 AM} 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:371)
[Error:033] {07:39:15 AM} 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
[Error:033] {07:39:15 AM} Caused by: com.android.apksig.zip.ZipFormatException: ZIP End of Central Directory record not found
[Error:033] {07:39:15 AM} 	at com.android.apksig.apk.ApkUtilsLite.findZipSections(ApkUtilsLite.java:49)
[Error:033] {07:39:15 AM} 	at com.android.apksig.apk.ApkUtils.findZipSections(ApkUtils.java:60)
[Error:033] {07:39:15 AM} 	at com.android.apksig.ApkSigner.sign(ApkSigner.java:233)
[Error:033] {07:39:15 AM} 	... 3 more
[Logs] {07:39:37 AM} Log saved successfully. D:\TUGAS_KULIAH\TOOL\Tools.Injector.Mod.Menu.v1.4.3.1\Logs\2021-8-14 07-39-37.txt


this is happening when using Full Compile Method 1 and Method 2, there is no problem when Compile Menu only

**Comment by darnkez** [comment] 2021-08-14 00:19
i'll just leave my discord here: EnderDog#5385
